name: Build for Windows
on: [workflow_dispatch]

jobs:
    build-win:
        name: Build for Windows
        runs-on: windows-latest
        strategy:
          fail-fast: false
          matrix:
              arch: [x64, ARM64]
              target: [Windows]

        steps:
          - uses: actions/checkout@v4
            with:
                submodules: recursive
          
          - name: Set project env vars
            shell: bash
            run: |
              BUILD_MODE=$(python3 -c "import json; print(json.load(open('assets/data/info.json'))['build-mode'])")
              BUILD_MODE_CAP=${BUILD_MODE^}

              echo "BUILD_MODE=$BUILD_MODE" >> $GITHUB_ENV
              echo "BUILD_MODE_CAP=$BUILD_MODE_CAP" >> $GITHUB_ENV

          - name: Run Windows build script
            shell: bash
            run: |
              ./config/win-build.sh --architecture=${{ matrix.arch }} --launch=false

          - name: Upload Build
            uses: actions/upload-artifact@v4
            if: ${{ matrix.target != 'WindowsStore' }}
            with: 
                name: ${{ env.PROJECT }}-${{ matrix.target }}-${{ matrix.arch }}
                path: |
                    build/${{ env.BUILD_MODE_CAP }}/${{ env.ASSETS_PATH }}
                    build/${{ env.BUILD_MODE_CAP }}/${{ env.PROJECT }}.exe
                    build/${{ env.BUILD_MODE_CAP }}/SDL3.dll
                    build/${{ env.BUILD_MODE_CAP }}/SDL3_image.dll
                    build/${{ env.BUILD_MODE_CAP }}/SDL3_mixer.dll
                    build/${{ env.BUILD_MODE_CAP }}/SDL3_ttf.dll
